morecat:
  image: emag/morecat
  links:
    - morecat-db:db
  ports:
    - 8080:8080
morecat-db:
  image: emag/morecat-db
  env_file:
    - .env
  volumes:
    - $HOME/morecat/pgdata/data:/var/lib/postgresql/data
  ports:
    - 5432:5432
