addSbtPlugin("io.spray" % "sbt-revolver" % "0.10.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.3")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.5")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.3")
addSbtPlugin("dev.zio" % "zio-sbt-ecosystem" % "0.4.0-alpha.34")
